import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  bidTypes: [
    {
      id: "1",
      airline: "AA",
      fleet: "73G",
      seat: "CAPTAIN",
      domicile: "ANC",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      id: "2",
      airline: "AA",
      fleet: "73G",
      seat: "CAPTAIN",
      domicile: "LAX",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      id: "3",
      fleet: "73G",
      airline: "AA",
      seat: "CAPTAIN",
      domicile: "PDX",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      id: "4",
      fleet: "73G",
      airline: "AA",
      seat: "CAPTAIN",
      domicile: "SEA",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      id: "5",
      fleet: "73G",
      airline: "AA",
      seat: "FIRST OFFICER",
      domicile: "ANC",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      id: "6",
      airline: "AA",
      fleet: "73G",
      seat: "FIRST OFFICER",
      domicile: "LAX",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      id: "7",
      airline: "AS",
      fleet: "73G",
      seat: "CAPTAIN",
      domicile: "LAX",
      status: "IMPORTING",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      id: "8",
      fleet: "73G",
      airline: "AS",
      seat: "CAPTAIN",
      domicile: "PDX",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      id: "9",
      fleet: "73G",
      airline: "AS",
      seat: "CAPTAIN",
      domicile: "SEA",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      id: "10",
      fleet: "73G",
      airline: "AS",
      seat: "FIRST OFFICER",
      domicile: "ANC",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      id: "11",
      airline: "AS",
      fleet: "73G",
      seat: "FIRST OFFICER",
      domicile: "LAX",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      id: "12",
      airline: "FA",
      fleet: "73G",
      seat: "CAPTAIN",
      domicile: "LAX",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      id: "13",
      fleet: "73G",
      airline: "FA",
      seat: "CAPTAIN",
      domicile: "PDX",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      id: "14",
      fleet: "73G",
      airline: "FA",
      seat: "CAPTAIN",
      domicile: "SEA",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      id: "15",
      fleet: "73G",
      airline: "FA",
      seat: "FIRST OFFICER",
      domicile: "ANC",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      id: "16",
      airline: "UP",
      fleet: "73G",
      seat: "FIRST OFFICER",
      domicile: "LAX",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      id: "17",
      airline: "UP",
      fleet: "73G",
      seat: "FIRST OFFICER",
      domicile: "LAX",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      id: "18",
      airline: "UP",
      fleet: "73G",
      seat: "FIRST OFFICER",
      domicile: "LAX",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
  ],
};

export const bidTypeSlice = createSlice({
  name: "bidTypes",
  initialState,
  reducers: {},
});

export const selectBidTypes = (state) => state.bidTypes.bidTypes; //state.store.objectInStore

export default bidTypeSlice.reducer;
