import {createSlice} from "@reduxjs/toolkit";

const initialState = {
  bidTypes: [
    {
      Id: "1",
      airline: "AA",
      fleet: "73G",
      seat: "CAPTAIN",
      domicile: "ANC",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      Id: "2",
      airline: "AA",
      fleet: "73G",
      seat: "CAPTAIN",
      domicile: "LAX",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      Id: "3",
      fleet: "73G",
      airline: "AA",
      seat: "CAPTAIN",
      domicile: "PDX",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      Id: "4",
      fleet: "73G",
      airline: "AA",
      seat: "CAPTAIN",
      domicile: "SEA",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      Id: "5",
      fleet: "73G",
      airline: "AA",
      seat: "FIRST OFFICER",
      domicile: "ANC",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      Id: "6",
      airline: "AA",
      fleet: "73G",
      seat: "FIRST OFFICER",
      domicile: "LAX",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      Id: "7",
      airline: "AS",
      fleet: "73G",
      seat: "CAPTAIN",
      domicile: "LAX",
      status: "IMPORTING",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      Id: "8",
      fleet: "73G",
      airline: "AS",
      seat: "CAPTAIN",
      domicile: "PDX",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      Id: "9",
      fleet: "73G",
      airline: "AS",
      seat: "CAPTAIN",
      domicile: "SEA",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      Id: "10",
      fleet: "73G",
      airline: "AS",
      seat: "FIRST OFFICER",
      domicile: "ANC",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      Id: "11",
      airline: "AS",
      fleet: "73G",
      seat: "FIRST OFFICER",
      domicile: "LAX",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      Id: "12",
      airline: "FA",
      fleet: "73G",
      seat: "CAPTAIN",
      domicile: "LAX",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      Id: "13",
      fleet: "73G",
      airline: "FA",
      seat: "CAPTAIN",
      domicile: "PDX",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      Id: "14",
      fleet: "73G",
      airline: "FA",
      seat: "CAPTAIN",
      domicile: "SEA",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      Id: "15",
      fleet: "73G",
      airline: "FA",
      seat: "FIRST OFFICER",
      domicile: "ANC",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      Id: "16",
      airline: "UP",
      fleet: "73G",
      seat: "FIRST OFFICER",
      domicile: "LAX",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      Id: "17",
      airline: "UP",
      fleet: "73G",
      seat: "FIRST OFFICER",
      domicile: "LAX",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
    {
      Id: "18",
      airline: "UP",
      fleet: "73G",
      seat: "FIRST OFFICER",
      domicile: "LAX",
      status: "CURRENT",
      numOfBidPeriods: 1,
      imported: new Date().toDateString(),
    },
  ],
};

export const bidTypeSlice = createSlice({
  name: "bidTypes",
  initialState,
  reducers: {
      
  }
});

export const selectBidTypes = (state) => state.bidTypes.bidTypes;  //state.store.objectInStore

export default bidTypeSlice.reducer;