import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import alex from "../../assets/img/alex-johnathan.jpeg";
import janet from "../../assets/img/janet-carton.jpeg";
import john from "../../assets/img/john-smith.jpeg";
import michael from "../../assets/img/michael-zimber.jpeg";
import monica from "../../assets/img/monica-smith.jpeg";
import sandra from "../../assets/img/sandra-smith.jpeg";
import { makeRequest } from "../../utils/makeRequest";

const avatar = {
  alex: { src: alex, alt: "Alex" },
  janet: { src: janet, alt: "Janet" },
  john: { src: john, alt: "John" },
  michael: { src: michael, alt: "Michael" },
  monica: { src: monica, alt: "Monica" },
  sandra: { src: sandra, alt: "Sandra" },
};

const initialState = {
  pilots: [
  {
    id: 1,
    airline: "AA",
    firstName: "John",
    lastName: "Smith",
    fleet: "737",
    seat: "CPT",
    domicile: "GEG",
    trainingFacility: "Riviera State 32/106",
    company: "American Airlines",
    address1: "795 Folsom Ave",
    address2: "Suite 600",
    city: "San Francisco",
    state: "CA",
    postalCode: "94107",
    areaCode: "123",
    prefix: "456",
    suffix: "7890",
    avatar: avatar.john,
  },
  {
    id: 2,
    airline: "AA",
    firstName: "Steve",
    lastName: "Strong",
    fleet: "737",
    seat: "FO",
    domicile: "GEG",
    trainingFacility: "Eastern State 32/106",
    company: "American Airlines",
    address1: "101 E Main ave",
    address2: "",
    city: "Spokane",
    state: "WA",
    postalCode: "99206",
    areaCode: "123",
    prefix: "456",
    suffix: "7890",
    avatar: avatar.john,
  },
  {
    id: 3,
    airline: "AA",
    firstName: "Peter",
    lastName: "Parker",
    fleet: "737",
    seat: "CPT",
    domicile: "GEG",
    trainingFacility: "Riviera State 32/106",
    company: "American Airlines",
    address1: "410 Chelsea St",
    address2: "apt 201",
    city: "Manhattan",
    state: "NY",
    postalCode: "10307",
    areaCode: "123",
    prefix: "456",
    suffix: "7890",
    avatar: avatar.john,
  },
  {
    id: 4,
    airline: "AA",
    firstName: "Johnny",
    lastName: "Blaze",
    fleet: "737",
    seat: "FO",
    domicile: "GEG",
    trainingFacility: "Riviera State 32/106",
    company: "American Airlines",
    address1: "795 Folsom Ave",
    address2: "Suite 600",
    city: "San Francisco",
    state: "CA",
    postalCode: "94107",
    areaCode: "123",
    prefix: "456",
    suffix: "7890",
    avatar: avatar.john,
  },
  {
    id: 5,
    airline: "AA",
    firstName: "Johathan Lowell Spencer",
    lastName: "Storm",
    fleet: "737",
    seat: "CPT",
    domicile: "GEG",
    trainingFacility: "Riviera State 32/106",
    company: "American Airlines",
    address1: "42nd Street and Madison Avenue",
    address2: "Suite 3401",
    city: "Manhattan",
    state: "NY",
    postalCode: "10017",
    areaCode: "123",
    prefix: "456",
    suffix: "7890",
    avatar: avatar.john,
  },
  {
    id: 6,
    airline: "AA",
    firstName: "Susan",
    lastName: "Storm",
    fleet: "737",
    seat: "FO",
    domicile: "GEG",
    trainingFacility: "Riviera State 32/106",
    company: "American Airlines",
    address1: "42nd Street and Madison Avenue",
    address2: "Suite 3201",
    city: "Manhattan",
    state: "NY",
    postalCode: "10017",
    areaCode: "123",
    prefix: "456",
    suffix: "7890",
    avatar: avatar.john,
  },
  {
    id: 7,
    airline: "AS",
    firstName: "Ben",
    lastName: "Grim",
    fleet: "737",
    seat: "CPT",
    domicile: "GEG",
    trainingFacility: "Riviera State 32/106",
    company: "Alaska Airlines",
    address1: "42nd Street and Madison Avenue",
    address2: "Suite 1001",
    city: "Manhattan",
    state: "NY",
    postalCode: "10017",
    areaCode: "123",
    prefix: "456",
    suffix: "7890",
    avatar: avatar.john,
  },
  {
    id: 8,
    airline: "AS",
    firstName: "Reed",
    lastName: "Richards",
    fleet: "737",
    seat: "FO",
    domicile: "GEG",
    trainingFacility: "Riviera State 32/106",
    company: "Alaska Airlines",
    address1: "42nd Street and Madison Avenue",
    address2: "Suite 3201",
    city: "Manhattan",
    state: "NY",
    postalCode: "10017",
    areaCode: "123",
    prefix: "456",
    suffix: "7890",
    avatar: avatar.john,
  },
  {
    id: 9,
    airline: "AS",
    firstName: "Tony",
    lastName: "Stark",
    fleet: "737",
    seat: "CPT",
    domicile: "GEG",
    trainingFacility: "Riviera State 32/106",
    company: "Alaska Airlines",
    address1: "10880 Malibu Point",
    address2: "",
    city: "Point Dume",
    state: "CA",
    postalCode: "90265",
    areaCode: "123",
    prefix: "456",
    suffix: "7890",
    avatar: avatar.john,
  },
  {
    id: 10,
    airline: "AS",
    firstName: "Natasha",
    lastName: "Romanova",
    fleet: "737",
    seat: "FO",
    domicile: "GEG",
    trainingFacility: "Riviera State 32/106",
    company: "Alaska Airlines",
    address1: "101 Main St",
    address2: "",
    city: "Concord",
    state: "NH",
    postalCode: "03301",
    areaCode: "123",
    prefix: "456",
    suffix: "7890",
    avatar: avatar.john,
  },
  {
    id: 11,
    airline: "AS",
    firstName: "Carol",
    lastName: "Danvers",
    fleet: "737",
    seat: "CPT",
    domicile: "GEG",
    trainingFacility: "Riviera State 32/106",
    company: "Alaska Airlines",
    address1: "820 W Rickshaw Ln",
    address2: "",
    city: "Beverly",
    state: "MA",
    postalCode: "01915",
    areaCode: "123",
    prefix: "456",
    suffix: "7890",
    avatar: avatar.john,
  },
  {
    id: 12,
    airline: "FA",
    firstName: "Wade",
    lastName: "Wilson",
    fleet: "737",
    seat: "FO",
    domicile: "GEG",
    trainingFacility: "Riviera State 32/106",
    company: "Frontier Airlines",
    address1: "215 East Hastings Street",
    address2: "Apt 215",
    city: "Vancouver",
    state: "WA",
    postalCode: "98607",
    areaCode: "123",
    prefix: "456",
    suffix: "7890",
    avatar: avatar.john,
  },
  {
    id: 13,
    airline: "FA",
    firstName: "James",
    lastName: "Howlett",
    fleet: "737",
    seat: "CPT",
    domicile: "GEG",
    trainingFacility: "Riviera State 32/106",
    company: "Frontier Airlines",
    address1: "1407 Graymalkin Lane",
    address2: "Room 7",
    city: "Salem Center",
    state: "NY",
    postalCode: "10560",
    areaCode: "123",
    prefix: "456",
    suffix: "7890",
    avatar: avatar.john,
  },
  {
    id: 14,
    airline: "FA",
    firstName: "Anna Marie",
    lastName: "LeBeau",
    fleet: "737",
    seat: "FO",
    domicile: "GEG",
    trainingFacility: "Riviera State 32/106",
    company: "Frontier Airlines",
    address1: "1407 Graymalkin Lane",
    address2: "Room 13",
    city: "Salem Center",
    state: "NY",
    postalCode: "10560",
    areaCode: "123",
    prefix: "456",
    suffix: "7890",
    avatar: avatar.john,
  },
  {
    id: 15,
    airline: "FA",
    firstName: "Max",
    lastName: "Eisenhardt",
    fleet: "737",
    seat: "CPT",
    domicile: "GEG",
    trainingFacility: "Riviera State 32/106",
    company: "Frontier Airlines",
    address1: "1407 Graymalkin Lane",
    address2: "Room 101",
    city: "Salem Center",
    state: "NY",
    postalCode: "10560",
    areaCode: "123",
    prefix: "456",
    suffix: "7890",
    avatar: avatar.john,
  },
  {
    id: 16,
    airline: "UP",
    firstName: "Remy Etienne",
    lastName: "LaBeau",
    fleet: "737",
    seat: "FO",
    domicile: "GEG",
    trainingFacility: "Riviera State 32/106",
    company: "UPS",
    address1: "1407 Graymalkin Lane",
    address2: "Room 13",
    city: "Salem Center",
    state: "NY",
    postalCode: "10560",
    areaCode: "123",
    prefix: "456",
    suffix: "7890",
    avatar: avatar.john,
  },
  {
    id: 17,
    airline: "UP",
    firstName: "Katherine",
    lastName: "Pryde",
    fleet: "737",
    seat: "CPT",
    domicile: "GEG",
    trainingFacility: "Riviera State 32/106",
    company: "UPS",
    address1: "1407 Graymalkin Lane",
    address2: "Room 12",
    city: "Salem Center",
    state: "NY",
    postalCode: "10560",
    areaCode: "123",
    prefix: "456",
    suffix: "7890",
    avatar: avatar.john,
  },
  {
    id: 18,
    airline: "UP",
    firstName: "Illyana",
    lastName: "Rasputina",
    fleet: "737",
    seat: "CPT",
    domicile: "GEG",
    trainingFacility: "Xavier's School 32/106",
    company: "UPS",
    address1: "1407 Graymalkin Lane",
    address2: "Room 27",
    city: "Salem Center",
    state: "NY",
    postalCode: "10560",
    areaCode: "123",
    prefix: "456",
    suffix: "7890",
    avatar: avatar.john,
  },
]};
export const loadPilots = createAsyncThunk("pilots/load", async () => {
  let res = await makeRequest(`/api/pilots/all`);
  return res.json();
});
export const pilotsSlice = createSlice({
  name: "pilots",
  initialState,
  reducers: {
    addPilot: {
      reducer: (state, action) => {
        state.pilots.push(action.payload);
      },
    },
  },
});

//export const addPilot = (state) => state.pilots;
export const {addPilot} = pilotsSlice.actions;

export default pilotsSlice.reducer;
